### ISSUE TITLE
What is LICENSE: Project's license? 

### ISSUE THREAD

**Issue by dealWIPdev** [beerose/theme-ui-sketchy#2]
Hello, 

What is` LICENSE: Project's license.`

On the ReadMe file LICENSE: Project's license, is described but there is no clear license statement. 

If this is an open-source project and the purpose of this theme is for other people to feel confident when selecting it.  Would you take a look at Github's helps for the licensing?

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Thanks.

**Comment by beerose** [comment]
Added.

**Comment by jjsub** [comment]
Thanks :)
